//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Technical_Software_Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class DailyTasks
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DailyTasks()
        {
            this.UserDailyTasks = new HashSet<UserDailyTasks>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string Image { get; set; }
        public int XP { get; set; }
        public int Score { get; set; }


        public bool IsCompleted { get; set; }
        public int CompletedCount { get; set; }
        public int TotalCount { get; set; }


        public int CompletionProgress
        {
            get { return this.CompletedCount; }
        }

        public void CompleteTask()
        {
            this.IsCompleted = true;
            foreach (var userTask in this.UserDailyTasks)
            {
                if (!userTask.IsCompleted)
                {
                    userTask.IsCompleted = true;
                    this.CompletedCount++;
                }
            }
        }

        public void CompleteSubtask()
        {
            this.CompletedCount++;
        }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserDailyTasks> UserDailyTasks { get; set; }
    }
}
